name: Size Limit CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  size-check:
    name: Check bundle size
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Run size-limit check
        uses: andresz1/size-limit-action@v1.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script_name: build
          package_manager: npm

